title: Data Science
description: Data Science Course for Bachelor Informatiekunde UvA
theme: just-the-docs

url: https://multix-amsterdam.github.io/data-science-course

aux_links:
  Template Repository: https://github.com/MultiX-Amsterdam/data-science-course
