title: MultiX Lab Docs
description: MultiX Lab Documentation
theme: just-the-docs

url: https://multix-amsterdam.github.io/multix-docs

aux_links:
  Repository: https://github.com/MultiX-Amsterdam/multix-docs
